dist: trusty
language: node_js
node_js:
- '8'
services:
- docker
addons:
  ssh_known_hosts: sinv-56034.edu.hsr.ch
  sonarcloud:
    organization: tourlive
    token:
      secure: LqqK6xF5mp+AOsZuE2n3HoRg+uPNluER+HzsLp8Ona5IzbU/3D54F1lgTx/akJZEHNSCmioXv9m7KPmp0RR5owV3ayPRsEBYDekow+imCisBimGXWPX6SII+ZKr+O40HhBQX8S7jMWlgvi7Gs4xoQrn9ep//5FMzr8kDmB3bWgEXgWy7oaU/0HK5MAIlUd4lsBxEER2oeXj6EEfWX7HbmCFFZCD/ZqR6NAhb/20vgsTHuf6FQba66Lg6B8KZvoJs1EElnOv7wLOIOGJTnu9nqf83AUgqrPU2fVLOAfg9Hc0gWT/CCXcwW+Pq1aEw+OfPZmMUQnCcTPwaRHzh/Xr1SlCZUIXbNbBFhr4CkUSw0FP0UsKq5/LsDzuuCMNFdWtOAm/T1XpT4D/xhLvrhVCpQfZdlaI7C8U3ZR9bpPeffn/XJnh9maT0wyhIrlmIfIsyONl+suuYVPzdmnn4iJKzi7iRSgcLS3p6fsmsp9b0eo8p9tLCeuyo/RALNxomChhb6mp6h4hKuWoe9RXjwFVXspcjrkOSqdna6uKR0873loiw6Y6BunuIDboq75xKUpAwaxsEXq6uLNGBDpjXicLtWA/lGz3nqJfpGuyPhLRz5pJ5Y0jgW3LluwEUNFgJpD9paU9GxVGSo/j6tYxNfqvLodpuxZzTdev88meJj/NQAMo=
cache:
  yarn: true
  directories:
  - "$HOME/.sonar/cache"
before_deploy:
- openssl aes-256-cbc -K $encrypted_1277f9814552_key -iv $encrypted_1277f9814552_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  script: bash docker_push
  on:
    branch: master
branches:
  only:
  - master
script:
- yarn test --coverage
- sonar-scanner
before_install:
- openssl aes-256-cbc -K $encrypted_814ec2fd2bf2_key -iv $encrypted_814ec2fd2bf2_iv -in deploy_rsa.enc -out deploy_rsa -d
