export const GET_SETTINGS = "GET_SETTINGS";
export const GET_RACES_AND_STAGES = "GET_RACES_STAGES";
export const SET_USER = "SET_USER";
export const UNSET_USER = "UNSET_USER";
export const SET_USER_ERROR = "SET_USER_ERROR";
export const SET_SETTINGS_ERROR = "SET_SETTINGS_ERROR";