const HOST = "http://localhost:9000";
const CNLAB_HOST = "https://tlng.cnlab.ch/";
export const LINK_SETTINGS = HOST + "/settings";
export const LINK_RACES = HOST + "/races";
export const LINK_LOGIN = HOST + "/login";
export const LINK_IMPORT = HOST + "/import";
export const LINK_UPDATE = HOST + "/update";
export const LINK_GPXTRACKS = HOST + "/gpxtracks/stages";
export const LINK_CNLAB_SETTINGS = CNLAB_HOST + "api/getAllGlobalSettings";